name = "Wildfire";
dir = "@wildfire";
author = "Seb";
actionName = "Website";
action = "http://www.carpenoctem.co";
description = "Github: https://github.com/Seb105/Arma-Wildfire";
tooltip = "Wildfire";
tooltipOwned = "Wildfire";
overview = "Spreadable wildfire";
overviewText = "Wildfire Overview";
logoSmall	 = "logoSmall.paa";	    // Display next to the item added by the mod
logo		 = "logo.paa";			// Logo displayed in the main menu
logoOver	 = "logoSmall.paa";	